apiVersion: v1
kind: Pod
metadata:
  name: productpage-cic
  labels:
    app: productpage-cic
spec:
      serviceAccountName: cpx
      containers:
      - name: productpage-cic
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.4.392"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
         - name: "NS_IP"
           value: "192.168.10.50"
         # Set username for the Nitro API
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "NO"
         - name: "NS_USER"
           value: "nsroot"
         - name: "NS_PASSWORD"
           value: "nsroot"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "DEBUG"
        args:
          - --ingress-classes
            vpx
          - --feature-node-watch
            false
        imagePullPolicy: IfNotPresent
